# Generated by Django 4.2.5 on 2023-10-18 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Quiz",
            new_name="Subject",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="quiz",
            new_name="subject",
        ),
        migrations.RenameField(
            model_name="score",
            old_name="quiz",
            new_name="subject",
        ),
    ]
