# Generated by Django 4.1 on 2023-11-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
