# Generated by Django 4.2.5 on 2023-10-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_quiz_subject_rename_quiz_question_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="attempts",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
