# Generated by Django 4.1 on 2023-11-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_grade_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='letter',
        ),
    ]
