# Generated by Django 4.2.5 on 2023-10-19 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_subject_attempts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="attempts",
        ),
    ]
