# Generated by Django 4.2.5 on 2023-11-14 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_remove_grade_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="main.subject",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="weight",
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
    ]
