# Generated by Django 4.2.5 on 2023-11-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_grade_score_alter_quiz_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
