# Generated by Django 4.2.5 on 2023-11-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_attempt_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="max_attempts",
            field=models.IntegerField(default=10),
        ),
    ]
