# Generated by Django 4.2.5 on 2023-11-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_semester_alter_grade_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="main.semester",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.semester",
            ),
        ),
    ]
