# Generated by Django 4.2.5 on 2023-11-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_grade_semester_subject_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="num",
            field=models.IntegerField(null=True),
        ),
    ]
