# Generated by Django 4.1 on 2023-11-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_semester_num_semester_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='current',
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
